# This is a makefile for the Cygwin tools which may
# be downloaded by following the links from the URL:
# http://sources.redhat.com/cygwin/

#
# Standard defines
#

CC = gcc
WRES = windres
LIBS = -s -mno-cygwin -mwindows -e _mainCRTStartup -lwinmm
CFLAGS = -Wall -W -pedantic -mno-cygwin -O2 -fno-strength-reduce -DWINDOWS

LUALIBS = -s -mno-cygwin

LUAOBJS = \
	lua/lapi.o lua/ldebug.o lua/lmem.o lua/lstrlib.o lua/lvm.o \
	lua/tolua_lb.o lua/lauxlib.o lua/ldo.o lua/lobject.o lua/ltable.o \
	lua/lzio.o lua/tolua_rg.o \
	lua/lbaselib.o lua/lfunc.o lua/lparser.o lua/ltests.o lua/tolua_bd.o \
	lua/tolua_tm.o lua/lcode.o lua/lgc.o lua/lstate.o lua/ltm.o \
	lua/tolua_eh.o lua/tolua_tt.o lua/ldblib.o lua/llex.o \
	lua/lstring.o lua/lundump.o lua/tolua_gp.o

TOLUAOBJS = \
	lua/tolua.o lua/tolualua.o lua/liolib.o \
	$(LUAOBJS)

OBJS = \
	angband.res birth.o cave.o \
	cmd1.o cmd2.o cmd3.o cmd4.o cmd5.o cmd6.o \
	interface.o help.o xmlbulp.o \
	resist.o dungeon.o files.o generate.o init1.o init2.o \
	main-win.o melee1.o melee2.o monster1.o monster2.o \
	object1.o object2.o randart.o readdib.o running.o \
	save.o spells1.o spells2.o debug.o \
	store.o tables.o util.o variable.o \
	wizard1.o wizard2.o xtra1.o xtra2.o \
	z-form.o z-rand.o z-term.o z-string.o z-virt.o \
	script.o l-monst.o l-object.o l-player.o l-random.o l-ui.o \
	l-misc.o l-spell.o l-dynamic.o \
	$(LUAOBJS)

HDRS = \
	h-basic.h h-define.h h-type.h h-system.h h-config.h

INCS = \
	angband.h config.h defines.h types.h externs.h script.h \
	z-term.h z-rand.h z-string.h z-misc.h z-virt.h z-form.h $(HDRS)

#
# Targets
#

default: nangband

install: nangband movebin cleanobjs

movebin:
	mv -f nangband.exe ../nangband.exe

cleanobjs:
	rm -f $(OBJS)
	rm -f $(TOLUAOBJS)

cleanbin:
	rm -f nangband.exe
	rm -f lua/tolua.exe

clean:	cleanobjs cleanbin

#
# Dependency rules
#

lua/tolua: $(TOLUAOBJS)
	$(CC) -o lua/tolua $(TOLUAOBJS) $(LUALIBS)

nangband: $(OBJS) $(INCS)
	$(CC) -o nangband $(OBJS) $(INCDIRS) $(LIBDIRS) $(LIBS)

#
# Compiling angband.rc
#

angband.res: angband.rc
	$(WRES) $< -O coff -o $@

#
# Compiling lua package files
#

l-monst.c: lua/tolua l-monst.pkg
	lua/tolua -n monster -o l-monst.c l-monst.pkg

l-object.c: lua/tolua l-object.pkg
	lua/tolua -n object -o l-object.c l-object.pkg

l-player.c: lua/tolua l-player.pkg
	lua/tolua -n player -o l-player.c l-player.pkg

l-random.c: lua/tolua l-random.pkg
	lua/tolua -n random -o l-random.c l-random.pkg

l-ui.c: lua/tolua l-ui.pkg
	lua/tolua -n ui -o l-ui.c l-ui.pkg

l-misc.c: lua/tolua l-misc.pkg
	lua/tolua -n misc -o l-misc.c l-misc.pkg

l-spell.c: lua/tolua l-spell.pkg
	lua/tolua -n spell -o l-spell.c l-spell.pkg

#
# Compiling objects
#

cmd5.o: cmd5.c $(INCS) script.h
cmd6.o: cmd6.c $(INCS) script.h
init1.o: init1.c $(INCS) init.h
init2.o: init2.c $(INCS) init.h script.h
l-misc.o: l-misc.c $(INCS) lua/tolua.h
l-monst.o: l-monst.c $(INCS) lua/tolua.h
l-object.o: l-object.c $(INCS) lua/tolua.h
l-player.o: l-player.c $(INCS) lua/tolua.h
l-random.o: l-random.c $(INCS) lua/tolua.h
l-spell.o: l-spell.c $(INCS) lua/tolua.h
l-ui.o: l-ui.c $(INCS) lua/tolua.h
randart.o: randart.c $(INCS) init.h
readdib.o: readdib.c readdib.h
script.o: script.c $(INCS) script.h
wizard2.o: wizard2.c $(INCS) script.h
xtra1.o: xtra1.c $(INCS) script.h
z-form.o: z-form.c $(HDRS) z-form.h z-string.h z-misc.h z-virt.h
z-rand.o: z-rand.c $(HDRS) z-rand.h
z-term.o: z-term.c $(HDRS) z-term.h z-virt.h
z-string.o: z-util.c $(HDRS) z-util.h
z-virt.o: z-virt.c $(HDRS) z-virt.h z-string.h z-misc.h

#
# Basic compiling data
#

.c.o: $(INCS)
	$(CC) $(CFLAGS) $(INCDIRS) -c -o $@ $<
